config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index-page'),
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls', "account")),
    path('store/', include('store.urls', "store")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('products/<uuid:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('products/<uuid:product_id>/add_to_cart/', views.AddToCartView.as_view(), name='add-to-cart'),
    path('products/<uuid:product_id>/review/', views.ReviewCreateView.as_view(), name='review'),
    path('products/<uuid:product_id>/toggle_like/', views.ToggleLikeView.as_view(), name='toggle-like'),
    path('products/<uuid:product_id>/toggle_dislike/', views.ToggleDislikeView.as_view(), name='toggle-dislike'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/<uuid:cart_item_id>/increase/', views.IncreaseQuantityView.as_view(), name='increase-cart-item'),
    path('cart/<uuid:cart_item_id>/decrease/', views.DecreaseQuantityView.as_view(), name='decrease-cart-item'),
    path('cart/<uuid:cart_item_id>/delete/', views.DeleteCartItemView.as_view(), name='delete-cart-item'),
    path('cart/shipping_address/', views.shippingAddressView, name='shipping-address'),
    path('callback_url/', views.callback, name='callback'),
    path('cart/checkout/', views.checkout, name='checkout'),
    path('orders/', views.OrderListView.as_view(), name='order-list'),
]

templates/partials/checkout_partial.html
            <p class="cart__product__price" id="product_price-{{ cart_item.id }}" hx-swap-oob="true"><b>&#8358; {{ cart_item.total_price }}</b></p>
                    <span class="cart__amount" id="product_quantity-{{ cart_item.id }}" hx-swap-oob="true">{{ cart_item.quantity }}</span>
<span id="total_price" hx-swap-oob="true">&#8358; {{ total_price }}</span>

templates/partials/flash_message_partial.html
<div id="flash-messages" hx-swap-oob="true">
    {% if messages %}
        {% for message in messages %}
            <i class="fa-solid fa-xmark close__message"></i>
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
</div>

templates/partials/home_partial.html
<main id="base" hx-swap-oob="true">
        {% include "searchbar.html" with search_query=search_query %}

{% include 'partials/product_list_partial.html' %}

</main>

templates/partials/like_and_dislike_partial.html
<span class="total_likes" id="total_likes" hx-swap-oob="true">{{ total_likes }}</span>

<span class="total_dislikes" id="total_dislikes" hx-swap-oob="true">{{ total_dislikes }}</span>

templates/partials/likes_partial.html
<p class="card__description" id="likes_section" hx-swap-oob="true">
            <!-- <span class="total_likes" id="total_likes">{{ total_likes }}</span> <i class="fa-regular fa-thumbs-up" hx-post="{% url 'store:toggle-like' product.id %}" hx-swap="none" hx-trigger="click"></i> <span id="total_dislikes" class="total_dislikes" >{{ total_dislikes }}</span>
            <i class="fa-regular fa-thumbs-down" hx-post="{% url 'store:toggle-dislike' product.id %}" hx-swap="none" hx-trigger="click"></i> -->
            {% if has_liked %}
            <span class="total_likes" id="total_likes">{{ total_likes }}</span> 
            <svg hx-post="{% url 'store:toggle-like' product.id %}"  hx-trigger="click" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M23 10a2 2 0 0 0-2-2h-6.32l.96-4.57c.02-.1.03-.21.03-.32c0-.41-.17-.79-.44-1.06L14.17 1L7.59 7.58C7.22 7.95 7 8.45 7 9v10a2 2 0 0 0 2 2h9c.83 0 1.54-.5 1.84-1.22l3.02-7.05c.09-.23.14-.47.14-.73zM1 21h4V9H1z"/></svg>
            <span id="total_dislikes" class="total_dislikes" >{{ total_dislikes }}</span>
            <svg hx-post="{% url 'store:toggle-dislike' product.id %}"  hx-trigger="click" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M19 15V3h4v12zM15 3a2 2 0 0 1 2 2v10c0 .55-.22 1.05-.59 1.41L9.83 23l-1.06-1.06c-.27-.27-.44-.64-.44-1.06l.03-.31l.95-4.57H3a2 2 0 0 1-2-2v-2c0-.26.05-.5.14-.73l3.02-7.05C4.46 3.5 5.17 3 6 3zm0 2H5.97L3 12v2h8.78l-1.13 5.32L15 14.97z"/></svg>
            {% elif has_disliked %}
            <span class="total_likes" id="total_likes">{{ total_likes }}</span> 
            <svg hx-post="{% url 'store:toggle-like' product.id %}"  hx-trigger="click" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M5 9v12H1V9zm4 12a2 2 0 0 1-2-2V9c0-.55.22-1.05.59-1.41L14.17 1l1.06 1.06c.27.27.44.64.44 1.05l-.03.32L14.69 8H21a2 2 0 0 1 2 2v2c0 .26-.05.5-.14.73l-3.02 7.05C19.54 20.5 18.83 21 18 21zm0-2h9.03L21 12v-2h-8.79l1.13-5.32L9 9.03z"/></svg>
            <span id="total_dislikes" class="total_dislikes" >{{ total_dislikes }}</span>
            <svg hx-post="{% url 'store:toggle-dislike' product.id %}"  hx-trigger="click" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M19 15h4V3h-4m-4 0H6c-.83 0-1.54.5-1.84 1.22l-3.02 7.05c-.09.23-.14.47-.14.73v2a2 2 0 0 0 2 2h6.31l-.95 4.57c-.02.1-.03.2-.03.31c0 .42.17.79.44 1.06L9.83 23l6.58-6.59c.37-.36.59-.86.59-1.41V5a2 2 0 0 0-2-2"/></svg>
            {% else %}
            <span class="total_likes" id="total_likes">{{ total_likes }}</span>
            <svg hx-post="{% url 'store:toggle-like' product.id %}"  hx-trigger="click" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M5 9v12H1V9zm4 12a2 2 0 0 1-2-2V9c0-.55.22-1.05.59-1.41L14.17 1l1.06 1.06c.27.27.44.64.44 1.05l-.03.32L14.69 8H21a2 2 0 0 1 2 2v2c0 .26-.05.5-.14.73l-3.02 7.05C19.54 20.5 18.83 21 18 21zm0-2h9.03L21 12v-2h-8.79l1.13-5.32L9 9.03z"/></svg>
            <span id="total_dislikes" class="total_dislikes" >{{ total_dislikes }}</span>
            <svg hx-post="{% url 'store:toggle-dislike' product.id %}"  hx-trigger="click" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M19 15V3h4v12zM15 3a2 2 0 0 1 2 2v10c0 .55-.22 1.05-.59 1.41L9.83 23l-1.06-1.06c-.27-.27-.44-.64-.44-1.06l.03-.31l.95-4.57H3a2 2 0 0 1-2-2v-2c0-.26.05-.5.14-.73l3.02-7.05C4.46 3.5 5.17 3 6 3zm0 2H5.97L3 12v2h8.78l-1.13 5.32L15 14.97z"/></svg>
            {% endif %}
</p>

templates/partials/order_list_partial.html
{% load static %}

<section class="main__content order_item__list">

{% for order_item in order_items %}
    <article class="card" hx-trigger="click" hx-get="{% url 'store:product-detail' order_item.product.id %}" hx-target="#base" hx-push-url="true">
{#        <figure class="card__image">#}
            <img src="{{ order_item.product.images.first.image.url}}" alt="{{ order_item.product.name }}" />
{#            <figcaption class="offscreen">{{ product.name }}/figcaption>#}
{#        </figure>#}
        <section class="card__text">
            <p class="card__name">{{ order_item.product.name }}</p>
            <p class="card__description">{{ order_item.product.description }}</p>
            <p class="card__description">{{ order_item.status }}</p>
            <p class="card__description">qty: {{ order_item.quantity }}</p>
            <p class="card__description">size: {{ order_item.size }}</p>
            <p class="card__price">UNIT PRICE: <span style="font-weight: bold">&#8358; </span>{{ order_item.unit_price }}</p>
            <p class="card__price">TOTAL PRICE: <span style="font-weight: bold">&#8358; </span>{{ order_item.total_price }}</p>


        </section>
    </article>
{% endfor %}

{% if is_paginated %}
<nav class="review__nav">
     {% if page_obj.has_previous %}
         <button type="button" hx-get="?page={{page_obj.previous_page_number}}"
            hx-target=".order_item__list" hx-push-url="true">previous</button>
     {% endif %}


    {% if page_obj.has_next %}
            <button type="button" hx-get="?page={{page_obj.next_page_number}}"
            hx-target=".order_item__list" hx-push-url="true"
            >next</button>
{#                <a href="?page={{ products.next_page_number }}">next</a>#}
{#                <a href="?page={{ products.paginator.num_pages }}">last &raquo;</a>#}
    {% endif %}

</nav>
{% endif %}

</section>

templates/partials/product_detail_partial.html
{% load static %}

   {% include "searchbar.html" %}


<section class="product__detail main__content"  x-data="dropdown">
{# product images #}
    <section class="images">
        <div class="main__image__div">
            <img class="main__image" src="{{ product.images.first.image.url }}" alt="shoe"  @click="toggleModal(); document.querySelector('.modal__image').src = $event.target.src"/>
        </div>
        <div class="other__images_div">
            {% for image in product.images.all %}
            <img class="other__image image_1" src="{{image.image.url}}" alt=""  @click="document.querySelector('.main__image').src=$el.src"/>
            {% endfor %}

        </div>
    </section>

{#  product details  #}
    <section class="details">
        <p><b>{{ product.brand }}</b> {{ product.name }}</p>
        <p>{{ product.description }}</p>
        <span id="total_reviews">{{ product.total_reviews }} review{{ product.total_reviews|pluralize }}</span>
        <!-- <p class="card__description">
            <span class="total_likes" id="total_likes">{{ total_likes }}</span> <i class="fa-regular fa-thumbs-up" hx-post="{% url 'store:toggle-like' product.id %}" hx-swap="none" hx-trigger="click"></i> <span id="total_dislikes" class="total_dislikes" >{{ total_dislikes }}</span>
            <i class="fa-regular fa-thumbs-down" hx-post="{% url 'store:toggle-dislike' product.id %}" hx-swap="none" hx-trigger="click"></i>
            {% if user_has_liked %}
            <span class="total_likes" id="total_likes">{{ total_likes }}</span> 
            <svg hx-post="{% url 'store:toggle-like' product.id %}" hx-swap="none" hx-trigger="click" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M23 10a2 2 0 0 0-2-2h-6.32l.96-4.57c.02-.1.03-.21.03-.32c0-.41-.17-.79-.44-1.06L14.17 1L7.59 7.58C7.22 7.95 7 8.45 7 9v10a2 2 0 0 0 2 2h9c.83 0 1.54-.5 1.84-1.22l3.02-7.05c.09-.23.14-.47.14-.73zM1 21h4V9H1z"/></svg>
            <span id="total_dislikes" class="total_dislikes" >{{ total_dislikes }}</span>
            <svg hx-post="{% url 'store:toggle-dislike' product.id %}" hx-swap="none" hx-trigger="click" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M19 15V3h4v12zM15 3a2 2 0 0 1 2 2v10c0 .55-.22 1.05-.59 1.41L9.83 23l-1.06-1.06c-.27-.27-.44-.64-.44-1.06l.03-.31l.95-4.57H3a2 2 0 0 1-2-2v-2c0-.26.05-.5.14-.73l3.02-7.05C4.46 3.5 5.17 3 6 3zm0 2H5.97L3 12v2h8.78l-1.13 5.32L15 14.97z"/></svg>
            {% elif user_has_disliked %}
            <span class="total_likes" id="total_likes">{{ total_likes }}</span> 
            <svg hx-post="{% url 'store:toggle-like' product.id %}" hx-swap="none" hx-trigger="click" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M5 9v12H1V9zm4 12a2 2 0 0 1-2-2V9c0-.55.22-1.05.59-1.41L14.17 1l1.06 1.06c.27.27.44.64.44 1.05l-.03.32L14.69 8H21a2 2 0 0 1 2 2v2c0 .26-.05.5-.14.73l-3.02 7.05C19.54 20.5 18.83 21 18 21zm0-2h9.03L21 12v-2h-8.79l1.13-5.32L9 9.03z"/></svg>
            <span id="total_dislikes" class="total_dislikes" >{{ total_dislikes }}</span>
            <svg hx-post="{% url 'store:toggle-dislike' product.id %}" hx-swap="none" hx-trigger="click" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M19 15h4V3h-4m-4 0H6c-.83 0-1.54.5-1.84 1.22l-3.02 7.05c-.09.23-.14.47-.14.73v2a2 2 0 0 0 2 2h6.31l-.95 4.57c-.02.1-.03.2-.03.31c0 .42.17.79.44 1.06L9.83 23l6.58-6.59c.37-.36.59-.86.59-1.41V5a2 2 0 0 0-2-2"/></svg>
            {% else %}
            <span class="total_likes" id="total_likes">{{ total_likes }}</span>
            <svg hx-post="{% url 'store:toggle-like' product.id %}" hx-swap="none" hx-trigger="click" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M5 9v12H1V9zm4 12a2 2 0 0 1-2-2V9c0-.55.22-1.05.59-1.41L14.17 1l1.06 1.06c.27.27.44.64.44 1.05l-.03.32L14.69 8H21a2 2 0 0 1 2 2v2c0 .26-.05.5-.14.73l-3.02 7.05C19.54 20.5 18.83 21 18 21zm0-2h9.03L21 12v-2h-8.79l1.13-5.32L9 9.03z"/></svg>
            <span id="total_dislikes" class="total_dislikes" >{{ total_dislikes }}</span>
            <svg hx-post="{% url 'store:toggle-dislike' product.id %}" hx-swap="none" hx-trigger="click" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M19 15V3h4v12zM15 3a2 2 0 0 1 2 2v10c0 .55-.22 1.05-.59 1.41L9.83 23l-1.06-1.06c-.27-.27-.44-.64-.44-1.06l.03-.31l.95-4.57H3a2 2 0 0 1-2-2v-2c0-.26.05-.5.14-.73l3.02-7.05C4.46 3.5 5.17 3 6 3zm0 2H5.97L3 12v2h8.78l-1.13 5.32L15 14.97z"/></svg>
            {% endif %}
        </p> -->
       <p class="card__description" id="likes_section">
            <!-- <span class="total_likes" id="total_likes">{{ total_likes }}</span> <i class="fa-regular fa-thumbs-up" hx-post="{% url 'store:toggle-like' product.id %}" hx-swap="none" hx-trigger="click"></i> <span id="total_dislikes" class="total_dislikes" >{{ total_dislikes }}</span>
            <i class="fa-regular fa-thumbs-down" hx-post="{% url 'store:toggle-dislike' product.id %}" hx-swap="none" hx-trigger="click"></i> -->
            {% if has_liked %}
            <span class="total_likes" id="total_likes">{{ total_likes }}</span> 
            <svg hx-post="{% url 'store:toggle-like' product.id %}" hx-swap="none" hx-trigger="click" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M23 10a2 2 0 0 0-2-2h-6.32l.96-4.57c.02-.1.03-.21.03-.32c0-.41-.17-.79-.44-1.06L14.17 1L7.59 7.58C7.22 7.95 7 8.45 7 9v10a2 2 0 0 0 2 2h9c.83 0 1.54-.5 1.84-1.22l3.02-7.05c.09-.23.14-.47.14-.73zM1 21h4V9H1z"/></svg>
            <span id="total_dislikes" class="total_dislikes" >{{ total_dislikes }}</span>
            <svg hx-post="{% url 'store:toggle-dislike' product.id %}" hx-swap="none" hx-trigger="click" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M19 15V3h4v12zM15 3a2 2 0 0 1 2 2v10c0 .55-.22 1.05-.59 1.41L9.83 23l-1.06-1.06c-.27-.27-.44-.64-.44-1.06l.03-.31l.95-4.57H3a2 2 0 0 1-2-2v-2c0-.26.05-.5.14-.73l3.02-7.05C4.46 3.5 5.17 3 6 3zm0 2H5.97L3 12v2h8.78l-1.13 5.32L15 14.97z"/></svg>
            {% elif has_disliked %}
            <span class="total_likes" id="total_likes">{{ total_likes }}</span> 
            <svg hx-post="{% url 'store:toggle-like' product.id %}" hx-swap="none" hx-trigger="click" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M5 9v12H1V9zm4 12a2 2 0 0 1-2-2V9c0-.55.22-1.05.59-1.41L14.17 1l1.06 1.06c.27.27.44.64.44 1.05l-.03.32L14.69 8H21a2 2 0 0 1 2 2v2c0 .26-.05.5-.14.73l-3.02 7.05C19.54 20.5 18.83 21 18 21zm0-2h9.03L21 12v-2h-8.79l1.13-5.32L9 9.03z"/></svg>
            <span id="total_dislikes" class="total_dislikes" >{{ total_dislikes }}</span>
            <svg hx-post="{% url 'store:toggle-dislike' product.id %}" hx-swap="none" hx-trigger="click" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M19 15h4V3h-4m-4 0H6c-.83 0-1.54.5-1.84 1.22l-3.02 7.05c-.09.23-.14.47-.14.73v2a2 2 0 0 0 2 2h6.31l-.95 4.57c-.02.1-.03.2-.03.31c0 .42.17.79.44 1.06L9.83 23l6.58-6.59c.37-.36.59-.86.59-1.41V5a2 2 0 0 0-2-2"/></svg>
            {% else %}
            <span class="total_likes" id="total_likes">{{ total_likes }}</span>
            <svg hx-post="{% url 'store:toggle-like' product.id %}" hx-swap="none" hx-trigger="click" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M5 9v12H1V9zm4 12a2 2 0 0 1-2-2V9c0-.55.22-1.05.59-1.41L14.17 1l1.06 1.06c.27.27.44.64.44 1.05l-.03.32L14.69 8H21a2 2 0 0 1 2 2v2c0 .26-.05.5-.14.73l-3.02 7.05C19.54 20.5 18.83 21 18 21zm0-2h9.03L21 12v-2h-8.79l1.13-5.32L9 9.03z"/></svg>
            <span id="total_dislikes" class="total_dislikes" >{{ total_dislikes }}</span>
            <svg hx-post="{% url 'store:toggle-dislike' product.id %}" hx-swap="none" hx-trigger="click" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M19 15V3h4v12zM15 3a2 2 0 0 1 2 2v10c0 .55-.22 1.05-.59 1.41L9.83 23l-1.06-1.06c-.27-.27-.44-.64-.44-1.06l.03-.31l.95-4.57H3a2 2 0 0 1-2-2v-2c0-.26.05-.5.14-.73l3.02-7.05C4.46 3.5 5.17 3 6 3zm0 2H5.97L3 12v2h8.78l-1.13 5.32L15 14.97z"/></svg>
            {% endif %}
</p>
    </section>
    


    {% if product.inventory  %}
{#  product form  #}
    <form hx-post="{% url 'store:add-to-cart' product.id %}" class="product__form" hx-swap="none">

        <input type="hidden" name="product_id" value="{{ product.id }}">

        <div>
            <label for="cars" style="font-weight: bold;">size:</label>
            <select id="size" name="size">
                {% for size in product.sizes.all %}
                <option value="{{ size.size }}">{{ size.size }}</option>
                {% endfor %}
            </select>
        </div>

        <button type="submit" class="btn">Add to cart</button>
    </form>
    {% endif %}




{% if user_has_bought %}

{% if request.user.is_authenticated and not user_has_reviewed %}
{#  review form  #}
<div id="review_form">
    <h4 class="review__title" @click="toggleReviewForm()" >Write a review</h4>
    <form x-show="openReviewForm" x-cloak x-transition class="review__form form" hx-post="{% url 'store:review' product.id %}" hx-trigger="submit" hx-target="#review_form" hx-swap="outerHTML">
    {% csrf_token %}
    <textarea name="review" id="review" placeholder="Write a review" required class="form__field"></textarea>
    <button type="submit" class="btn">Submit</button>
    </form>
</div>
{% endif %}

{% endif %}


{#  product review  #}
<div id="reviews">
{% if product.has_reviews %}
    <h4 @click="toggle()" x-text="open ? close : show" class="review__title"></h4>
    <section class="reviews" x-show="open" x-transition x-cloak>
        
        <section class="reviews" >
        {% for review in product.reviews.all %}
            <div class="single__review">
                <p class="review__username"><b>{{ review.user.get_full_name }}</b> <span class="review_date">{{ review.created_at }}</span></p>
                <p>{{ review.review | linebreaksbr }}</p>
            </div>
        {% endfor %}
        </section>
        <!-- <nav x-show="open" class="review__nav" x-transition x-cloak>
            <button type="button">previous</button>
            <button>next</button>
        </nav> -->
    </section>
{% endif %}
</div>

{#  modal  #}
    <figure class="modal__figure" x-cloak x-show="openModal" x-transition>
        <i class="fa-solid fa-xmark modal__close" @click="toggleModal()"></i>
    <img class="modal__image" src="" @click.outside="openModal ? toggleModal() : '' " alt="shoe">
        <figcaption class="offscreen">Photo name</figcaption>
    </figure>

</section>

templates/partials/product_list_partial.html
{% load static %}

<section class="main__content product__list">
{% for product in products %}
    <article class="card" hx-trigger="click" hx-get="{% url 'store:product-detail' product.id %}" hx-target="#base" hx-push-url="true">
{#        <figure class="card__image">#}
            <img src="{{ product.images.first.image.url}}" alt="{{ product.name }}" />
{#            <figcaption class="offscreen">{{ product.name }}/figcaption>#}
{#        </figure>#}
        <section class="card__text">
            <p class="card__name">{{ product.name }}</p>
            <p class="card__description">{{ product.description }}</p>
            {% if product.orders %}
            <p class="card__description">{{ product.orders.count }} sold</p>
            {% else %}
                <p class="card__description">0 sold</p>
            {% endif %}
            <p class="card__description">{{ product.total_reviews }} review{{product.total_reviews|pluralize}}</p>
            <p class="card__price"><span style="font-weight: bold">&#8358; </span>{{ product.unit_price }}</p>
            
        </section>
    </article>
{% endfor %}

{% if is_paginated %}
<nav class="review__nav">
     {% if page_obj.has_previous %}
         <button type="button" hx-get="?page={{page_obj.previous_page_number}}"
            hx-target=".product__list" hx-push-url="true">previous</button>
     {% endif %}


    {% if page_obj.has_next %}
            <button type="button" hx-get="?page={{page_obj.next_page_number}}"
            hx-target=".product__list" hx-push-url="true"
            >next</button>
{#                <a href="?page={{ products.next_page_number }}">next</a>#}
{#                <a href="?page={{ products.paginator.num_pages }}">last &raquo;</a>#}
    {% endif %}

</nav>
{% endif %}

</section>

templates/partials/review_partial.html
<div id="reviews" hx-swap-oob="true">
{% if product.has_reviews %}
    <h4 @click="toggle()" x-text="open ? close : show" class="review__title"></h4>
    <section class="reviews" x-show="open" x-transition x-cloak>
        
        <section class="reviews" >
        {% for review in product.reviews.all %}
            <div class="single__review">
                <p class="review__username"><b>{{ review.user.get_full_name }}</b> <span class="review_date">{{ review.created_at }}</span></p>
                <p>{{ review.review }}</p>
            </div>
        {% endfor %}
        </section>
        <!-- <nav x-show="open" class="review__nav" x-transition x-cloak>
            <button type="button">previous</button>
            <button>next</button>
        </nav> -->
    </section>
{% endif %}
</div>

<div id="review_form" hx-swap-oob="true">
</div>

<span id="total_reviews" hx-swap-oob="true">{{ product.total_reviews }} reviews</span>

templates/partials/shipping_address_partial_form.html
<form action="" method="POST" >
    {% csrf_token %}
    <label for="address" class='field__label'>Shipping Address</label>
    <input type="text" required class="form__field" name="address" id="address">
    <button type="submit" class="form__button">Submit</button>
</form>

templates/partials/total_price_partial.html
<span id="total_price" hx-swap-oob="true">&#8358; {{ total_price }}</span>
<div id="cart__item-{{cart_item_id}}" hx-swap-oob="true"></div>