account/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('verify_user/', TemplateView.as_view(template_name='account/verify_user.html'), name='verify_user'),
    path('verify/<str:token>/', views.verify, name='verify'),
    path('generate_token/<str:pk>/', views.generate_token, name='token_generator'),
    path('login/', views._login, name='login'),
    path("reset_password/", views.reset_password, name='reset_password'), # login required
    path("create_new_password/<str:token>/", views.create_new_password, name='create_new_password'),
    path("logout/", views._logout, name='logout'),
    path("address/", views.CreateAddress.as_view(), name='address'),
    path("update_address/", views.UpdateAddress.as_view(), name='update_address'),
    path("update", views.UpdateUser.as_view(), name='update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index-page'),
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls', "account")),
    path('store/', include('store.urls', "store")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('products/<uuid:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('products/<uuid:product_id>/add_to_cart/', views.AddToCartView.as_view(), name='add-to-cart'),
    path('products/<uuid:product_id>/review/', views.ReviewCreateView.as_view(), name='review'),
    path('products/<uuid:product_id>/toggle_like/', views.ToggleLikeView.as_view(), name='toggle-like'),
    path('products/<uuid:product_id>/toggle_dislike/', views.ToggleDislikeView.as_view(), name='toggle-dislike'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/<uuid:cart_item_id>/increase/', views.IncreaseQuantityView.as_view(), name='increase-cart-item'),
    path('cart/<uuid:cart_item_id>/decrease/', views.DecreaseQuantityView.as_view(), name='decrease-cart-item'),
    path('cart/<uuid:cart_item_id>/delete/', views.DeleteCartItemView.as_view(), name='delete-cart-item'),
    path('cart/shipping_address/', views.shippingAddressView, name='shipping-address'),
    path('callback_url/', views.callback, name='callback'),
    path('cart/checkout/', views.checkout, name='checkout'),
    path('orders/', views.OrderListView.as_view(), name='order-list'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="A fashion store">
    <meta name="Author" content="Praise Josiah and Gabriel Emmanuel">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/a2a2a7fc76.js" crossorigin="anonymous"></script>
    <link href="{% static 'css/index.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
    <link rel="stylesheet" href="{% static 'css/already_verified.css' %}">
    <link rel="stylesheet" href="{% static 'css/password__rest_form.css' %}">
    <link rel="stylesheet" href="{% static 'css/generateToken.css' %}">
    <link rel="stylesheet" href="{% static 'css/verify_user.css' %}">
    <link rel="stylesheet" href="{% static 'css/flash_message.css' %}">
    <script src="{% static 'js/htmx.min.js' %}"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <title>Dale Stores</title>
</head>

<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    {% include 'header.html' %}
    {% include 'partials/flash_message_partial.html' %}

    <main id="base">
        {% block content %}

        {% endblock content %}
    </main>


</body>
<script src="{% static 'js/alpine_script.js' %}"></script>
<script src="{% static 'js/generateToken.js' %}"></script>
<script src="{% static 'js/flash_message.js' %}"></script>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% include "searchbar.html" %}

<section class="cart main__content">
    
    {% for item in cart_items %}

        {% if item.cart_item.product.in_stock %}
    <div class="cart__item" id="cart__item-{{item.cart_item.id}}">
        <figure class="cart__image">
            <img src="{{ item.image }}" alt="{{ item.cart_item.product.name }}" />
            <figcaption class="offscreen">{{ item.cart_item.product.name }}</figcaption>
        </figure>
        <div class="cart__text">
            <p><b>{{ item.cart_item.product.brand }}</b> {{ item.cart_item.product.name }}</p>
            <p>{{ item.cart_item.product.description }}</p>
            <p class="size">size: {{ item.cart_item.size }}</p>
            <p class="cart__product__price" id="product_price-{{ item.cart_item.id }}"><b>&#8358; {{ item.cart_item.total_price }}</b></p>
            <p class="button__con">
                <span class="cart__button">
                     <span class="cart__subtract" hx-trigger="click" hx-post="{% url 'store:decrease-cart-item' item.cart_item.id %}" hx-swap="none">
                        <i class="fa-solid fa-minus"></i>
                    </span>
                    <span class="cart__amount" id="product_quantity-{{ item.cart_item.id }}">{{ item.cart_item.quantity }}</span>
                    <span class="cart__add" hx-trigger="click" hx-post="{% url 'store:increase-cart-item' item.cart_item.id %}" hx-swap="none">
                        <i class="fa-solid fa-plus"></i>
                    </span>
                   
                </span>
                <i class="fa-solid fa-trash" hx-trigger="click" hx-delete="{% url 'store:delete-cart-item' item.cart_item.id %}"></i>
            </p>
        </div>
    </div>
        {% else %}
            <div class="cart__item" id="cart__item-{{item.cart_item.id}}">
        <figure class="cart__image">
            <img src="{{ item.image }}" alt="{{ item.cart_item.product.name }}" />
            <figcaption class="offscreen">{{ item.cart_item.product.name }}</figcaption>
        </figure>
        <div class="cart__text">
            <p><b>{{ item.cart_item.product.brand }}</b> {{ item.cart_item.product.name }}</p>
            <p>{{ item.cart_item.product.description }}</p>
            <p class="size">size: {{ item.cart_item.size }}</p>
            <p class="cart__product__price" id="product_price-{{ item.cart_item.id }}"><b>&#8358; {{ item.cart_item.total_price }}</b></p>
            <p class="button__con">
                <span>Out of stock</span>
                <i class="fa-solid fa-trash" hx-trigger="click" hx-delete="{% url 'store:delete-cart-item' item.cart_item.id %}"></i>
            </p>
        </div>
    </div>

        {% endif %}
    {% endfor %}
    
    <p class="checkout" hx-get="{%  url 'store:checkout' %}" hx-swap="none"><button class="checkout__btn">Checkout <span id="total_price">&#8358; {{ total_price }}</span></button></p>
    {#  <p><a hx-get="{%  url 'store:checkout' %}" hx-swap="none">Cghjheckout <span id="total_price">&#8358; {{ total_price }}</span</a></p> #}

</section>

{% endblock content %}

templates/header.html
{% load static %}

<header class="header" x-data="dropdown" >
    <h1 class="header__logo">Dale Stores</h1>
    <i class="fa-solid fa-bars menu--open" @click="toggleMenu()"></i>
    <ul class="menu">
        <i class="fa-solid fa-xmark menu--close" @click="toggleMenu()"></i>
        <li class="menu__link menu__link--active">
		<p><i class="fa-solid fa-house nav-icon"></i><a href="{% url 'index-page' %}">Home</a></p>
        </li>
        <li class="menu__link">
            <p><i class="fa-solid fa-shop nav-icon"></i><a href="{% url 'store:product-list' %}"  hx-swap='none' hx-get="{% url 'store:product-list' %}?to=home" @click="toggleMenu()" hx-push-url="true">Shop</a></p>
        </li>
        <li class="menu__link category--list" @click="document.querySelector('.menu__sublink--first').classList.toggle('hidden')">
            <p><i class="fa-solid fa-person nav-icon"></i> <span>Men</span></p>
            <ul class="menu__sublink hidden menu__sublink--first">
                  <li>
                    <a href="{% url 'store:product-list' %}?category=shoes&gender=male" hx-get="{% url 'store:product-list' %}?category=shoes&gender=male" hx-target=".main__content" hx-push-url="true" @click="toggleMenu()">Shoes</a>
                </li>
                <li>
                    <a href="{% url 'store:product-list' %}?category=clothes&gender=male" hx-get="{% url 'store:product-list' %}?category=clothes&gender=male" hx-target=".main__content" hx-push-url="true" @click="toggleMenu()">Clothes</a>
                </li>
                <li>
                    <a href="{% url 'store:product-list' %}?category=bags&gender=male" hx-get="{% url 'store:product-list' %}?category=bags&gender=male" hx-target=".main__content" hx-push-url="true" @click="toggleMenu()">Bags</a>

                </li>
                <li>
                    <a href="{% url 'store:product-list' %}?category=accessories&gender=male" hx-target=".main__content" hx-get="{% url 'store:product-list' %}?category=accessories&gender=male" hx-push-url="true" @click="toggleMenu()">Accessories</a>

                </li>
            </ul>
        </li>
        <li class="menu__link category--list" @click="document.querySelector('.menu__sublink--second').classList.toggle('hidden')">
            <p><i class="fa-solid fa-person-dress nav-icon"></i><span>Women</span></p>
            <ul class="menu__sublink menu__sublink--second hidden">
                <li>
                    <a href="{% url 'store:product-list' %}?category=shoes&gender=female" hx-target=".main__content" hx-get="{% url 'store:product-list' %}?category=shoes&gender=female" hx-push-url="true" @click="toggleMenu()">Shoes</a>
                </li>
                <li>
                    <a href="{% url 'store:product-list' %}?category=clothes&gender=female" hx-target=".main__content" hx-get="{% url 'store:product-list' %}?category=clothes&gender=female" hx-push-url="true" @click="toggleMenu()">Clothes</a>
                </li>
                <li>
                    <a href="{% url 'store:product-list' %}?category=bags&gender=female" hx-target=".main__content" hx-get="{% url 'store:product-list' %}?category=bags&gender=female" hx-push-url="true" @click="toggleMenu()">Bags</a>

                </li>
                <li>
                    <a href="{% url 'store:product-list' %}?category=accessories&gender=female" hx-target=".main__content" hx-get="{% url 'store:product-list' %}?category=accessories&gender=female" hx-push-url="true" @click="toggleMenu()">Accessories</a>

                </li>
            </ul>
        </li>
        <li class="menu__link">
            <p><i class="fa-solid fa-cart-shopping nav-icon"></i><a @click="toggleMenu()" href="{% url 'store:cart' %}">Cart</a></p>
        </li>
        <li class="menu__link">
            <p><i class="fa-solid fa-house nav-icon"></i><a href="{% url 'store:order-list' %}"  hx-target=".main__content" hx-get="{% url 'store:order-list' %}?to=home" @click="toggleMenu()" hx-push-url="true">Orders</a></p>
        </li>
        <li class="menu__link">
            {% if request.user.is_authenticated %}
            <p><i class="fa-solid fa-right-to-bracket nav-icon"></i> <a href="{% url 'account:logout' %}" @click="toggleMenu()">Logout</a></p>
            {% else %}
            <p><i class="fa-solid fa-right-to-bracket nav-icon"></i> <a href="{% url 'account:login' %}" @click="toggleMenu()">Login</a></p>
            {% endif %}
        </li>

    </ul>
</header>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dale Store</title>
    <link rel="stylesheet" href="{% static 'css/indx.css' %}" />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <!-- Hero Section -->
    <section class="hero">
      <div class="hero-left">
        <h2>Welcome to</h2>
        <p>Dale Stores</p>
        <p>Express yourself through fashion</p>
        <a href="/store/products/">Go To Store</a>
      </div>
      <div class="hero-right">
	      <img src="{% static 'images/hero_image.png' %}" alt="hero image" />
      </div>
    </section>
  </body>
</html>

templates/orders_list.html
{% extends "base.html" %}
{% load static %}


{% block content %}


{% include 'partials/order_list_partial.html' %}

{% endblock %}

templates/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

{% include 'partials/product_detail_partial.html' %}

{% endblock content %}

templates/product_list.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    {% include "searchbar.html" with search_query=search_query %}

{% include 'partials/product_list_partial.html' %}

{% endblock %}

templates/searchbar.html
    <form hx-get="{% url 'store:product-list' %}" hx-target=".main__content" hx-push-url="true" class="search-bar">
        <input type="search" name="q" placeholder="Search...." value="{{ search_query }}">
        <button type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>

templates/shipping_address_form.html
{% extends 'base.html' %}

{% block content %}

<section class="main__content">

{% include 'partials/shipping_address_partial_form.html' %}

</section>

{% endblock content %}